status_topic_name: status
close_service_name: close
open_service_name: open

ur_io_service_name: ur_hardware_interface/set_io
update_joints_service_name: joint_position_publisher/set_joints

min_opening: 0.0054
max_opening: 0.110

left_joint: robot_wsg50_finger_left_joint
left_joint_direction: -1


right_joint: robot_wsg50_finger_right_joint
right_joint_direction: 1
