status_topic_name: status
close_service_name: close
open_service_name: open

ur_io_service_name: ur_hardware_interface/set_io
update_joints_service_name: joints_updater/set_joints

left_joint: egh_left_finger_joint
left_joint_open_position: 0.0
left_joint_close_position: -0.3

right_joint: egh_right_finger_joint
right_joint_open_position: 0.0
right_joint_close_position: -0.3